### ISSUE TITLE
8/18/2023 update crashes on startup

### ISSUE THREAD

**Issue by hancockjt** [openshift/custom-domains-operator#128]
The latest PR merge got auto-updated in our clusters and the operator pod crashes on every startup attempt.

```shell
2023-08-18T15:24:07Z INFO setup starting manager
2023-08-18T15:24:07Z INFO Starting server {"kind": "health probe", "addr": "[::]:8081"}
2023-08-18T15:24:07Z INFO starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2023-08-18T15:24:07Z INFO Starting EventSource {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain", "source": "kind source: *v1alpha1.CustomDomain"}
2023-08-18T15:24:07Z INFO Starting EventSource {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain", "source": "kind source: *v1.IngressController"}
2023-08-18T15:24:07Z INFO Starting EventSource {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain", "source": "kind source: *v1.Secret"}
2023-08-18T15:24:07Z INFO Starting Controller {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain"}
2023-08-18T15:24:07Z INFO Starting workers {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain", "worker count": 1}
2023-08-18T15:24:07Z INFO controller_customdomain Reconciling CustomDomain {"Request.Namespace": "", "Request.Name": "app-domain"}
2023-08-18T15:24:07Z INFO controller_customdomain Secret change detected, updating certificate. {"Request.Namespace": "", "Request.Name": "app-domain"}
2023-08-18T15:24:08Z INFO Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference {"controller": "customdomain", "controllerGroup": "managed.openshift.io", "controllerKind": "CustomDomain", "CustomDomain": {"name":"app-domain"}, "namespace": "", "name": "app-domain", "reconcileID": "df5fcd89-23cf-44ca-a433-9256e4567ac3"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1524186]
goroutine 119 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x1697800, 0x28b8990})
/usr/lib/golang/src/runtime/panic.go:884 +0x212
github.com/openshift/custom-domains-operator/controller.(*CustomDomainReconciler).Reconcile(0xc0000b5800, {0x1b40598?, 0xc0047ca330?}, {{{0x0?, 0x10?}, {0xc0004bf826?, 0x413247?}}})
/src/controller/customdomain_controller.go:368 +0x1466
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1b40598?, {0x1b40598?, 0xc0047ca330?}, {{{0x0?, 0x161cf20?}, {0xc0004bf826?, 0x10?}}})
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002c2960, {0x1b404f0, 0xc0002c0640}, {0x1716b80?, 0xc00017e5c0?})
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002c2960, {0x1b404f0, 0xc0002c0640})
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x333
```

**Comment by mjlshen** [comment]
Thanks for reporting! We ended up reverting the change in https://github.com/openshift/custom-domains-operator/pull/127
